import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { File, Paths } from "expo-file-system";

export function escapeHtml(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export function createSermonPdfHtml(sermon, exportDate = new Date()) {
  const rows = [
    ["Preacher", sermon.preacher], ["Church", sermon.church], ["Date", sermon.date], ["Key Scripture", sermon.scripture],
  ].filter(([, value]) => String(value ?? "").trim());
  const metadata = rows.map(([label, value]) => `<div class="row"><div class="label">${label}</div><div class="value">${escapeHtml(value)}</div></div>`).join("");
  const notes = escapeHtml(sermon.notes || "").replace(/\r\n|\r|\n/g, "<br>");
  const date = escapeHtml(exportDate.toLocaleDateString());

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
    @page { margin: 48px 44px 54px; }
    * { box-sizing: border-box; }
    body { margin: 0; color: #1f2937; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif; font-size: 14px; line-height: 1.6; }
    .brand { color: #123524; font-size: 28px; font-weight: 800; margin: 0; }
    .subtitle { color: #166534; font-size: 15px; font-weight: 700; margin: 2px 0 28px; }
    h1 { color: #123524; font-size: 25px; line-height: 1.25; margin: 0 0 20px; }
    .metadata { border: 1px solid #d1d5db; border-radius: 8px; margin-bottom: 28px; overflow: hidden; }
    .row { display: flex; padding: 9px 12px; border-bottom: 1px solid #e5e7eb; break-inside: avoid; page-break-inside: avoid; }
    .row:last-child { border-bottom: 0; }
    .label { color: #166534; font-weight: 700; width: 125px; flex-shrink: 0; }
    .value { flex: 1; }
    h2 { color: #123524; font-size: 18px; margin: 0 0 10px; break-after: avoid; page-break-after: avoid; }
    .notes { white-space: normal; overflow-wrap: anywhere; }
    .footer { color: #6b7280; font-size: 10px; margin-top: 34px; padding-top: 10px; border-top: 1px solid #e5e7eb; }
  </style></head><body>
    <p class="brand">Nkwa Bible</p><p class="subtitle">Sermon Note</p>
    <h1>${escapeHtml(sermon.title || "Sermon")}</h1>
    ${metadata ? `<section class="metadata">${metadata}</section>` : ""}
    ${notes ? `<section><h2>Sermon Notes</h2><div class="notes">${notes}</div></section>` : ""}
    <div class="footer">Generated by Nkwa Bible · ${date}</div>
  </body></html>`;
}

export function createSermonPdfFilename(sermon) {
  const raw = [sermon.title, sermon.date].filter(Boolean).join("-");
  const safe = raw.normalize("NFKD").replace(/[\\/:*?"<>|]/g, "-").replace(/[^a-zA-Z0-9._-]+/g, "-").replace(/-+/g, "-").replace(/^[-.]+|[-.]+$/g, "").slice(0, 90);
  return safe ? `${safe}.pdf` : "Nkwa-Bible-Sermon.pdf";
}

export async function exportSermonToPdf(sermon) {
  if (!sermon || typeof sermon !== "object") throw new Error("A valid sermon is required for PDF export.");
  if (!(await Sharing.isAvailableAsync())) {
    const error = new Error("Sharing is not available on this device.");
    error.code = "SHARING_UNAVAILABLE";
    throw error;
  }

  const result = await Print.printToFileAsync({ html: createSermonPdfHtml(sermon) });
  const source = new File(result.uri);
  const filename = createSermonPdfFilename(sermon);
  const namedFile = new File(Paths.cache, filename);

  try {
    await source.copy(namedFile, { overwrite: true });
    await Sharing.shareAsync(namedFile.uri, { mimeType: "application/pdf", UTI: "com.adobe.pdf", dialogTitle: "Export sermon note" });
    return { numberOfPages: result.numberOfPages, filename, shared: true };
  } finally {
    try { await namedFile.delete(); } catch (cleanupError) { console.warn("Unable to remove the temporary sermon PDF.", cleanupError); }
    try { await source.delete(); } catch (cleanupError) { console.warn("Unable to remove the generated sermon PDF.", cleanupError); }
  }
}
