from pathlib import Path
from base64 import b64encode
from html import escape
from datetime import date

OUT = Path(__file__).parent
LOGIN = Path('/private/tmp/ledgify-login.png')

def h(level, text, ident=None):
    anchor = ident or ''.join(c.lower() if c.isalnum() else '-' for c in text).strip('-')
    return f'<h{level} id="{anchor}">{escape(text)}</h{level}>'

def p(text, cls=''):
    return f'<p class="{cls}">{text}</p>'

def ul(items):
    return '<ul>' + ''.join(f'<li>{item}</li>' for item in items) + '</ul>'

def ol(items):
    return '<ol>' + ''.join(f'<li>{item}</li>' for item in items) + '</ol>'

def table(headers, rows):
    return '<table><thead><tr>' + ''.join(f'<th>{x}</th>' for x in headers) + '</tr></thead><tbody>' + ''.join('<tr>' + ''.join(f'<td>{c}</td>' for c in row) + '</tr>' for row in rows) + '</tbody></table>'

def note(kind, title, text):
    return f'<aside class="{kind}"><strong>{title}</strong><p>{text}</p></aside>'

def shot(caption):
    return f'<figure class="placeholder"><div>AUTHENTICATED SCREENSHOT REQUIRED<br><small>{escape(caption)}</small></div><figcaption>{escape(caption)} — add after a sanitised seeded session is available.</figcaption></figure>'

def chapter(num, title, body):
    return f'<section class="chapter">{h(1, f"{num}. {title}", f"chapter-{num}")}{body}</section>'

toc_titles = [
('1','Introduction to Ledgify'),('2','Getting started'),('3','Initial organisation setup'),('4','Accounting fundamentals'),
('5','Dashboard'),('6','Sales and accounts receivable'),('7','Purchases and accounts payable'),('8','Banking'),
('9','Chart of Accounts'),('10','Journals'),('11','Inventory'),('12','Fixed Assets'),('13','Manufacturing'),
('14','Reports and financial analysis'),('15','Tax, payroll, currencies and consolidation'),('16','Settings'),
('17','Users, roles and permissions'),('18','AI Assistant'),('19','Search, notifications and profile'),
('20','Imports, exports and attachments'),('21','Period-end procedures'),('22','Common workflows'),
('23','Troubleshooting'),('24','Internal controls and good practice'),('25','Glossary'),('26','Frequently asked questions'),
('27','Appendices')]

cover = '''<section class="cover"><div class="brand">LEDGIFY</div><h1>Complete User Manual</h1><div class="rule"></div><p>Release Candidate 1 · Document version 1.0</p><p>Prepared 26 August 2026</p><p class="audience">For business owners, accountants, bookkeepers and authorised users</p><p class="confidential">Customer-facing operational guide</p></section>'''

control = '<section class="front">' + h(1,'Document control','document-control') + table(['Item','Details'],[
('Version','1.0'),('Date','26 August 2026'),('Status','Complete manual for Ledgify RC1'),('Purpose','Explain the implemented Ledgify workflows and their accounting effect.'),
('Audience','Business owners, accountants, bookkeepers and authorised users.'),('Scope','Implemented web application features, connected backend workflows and clearly identified limitations.'),
('Example business','Northstar Trading Ltd, a fictional UK company using GBP.'),('Basis','Frontend routes and forms, backend models, serializers, permissions, services, tests and RC1 status documentation.')])
control += note('warning','Important disclaimer','Ledgify supports record-keeping and analysis; it does not replace professional accounting, tax or legal advice. Users remain responsible for source documents, classifications, approvals, filings and statutory compliance. Test material and examples must not be treated as advice for a real organisation.') + '</section>'

toc = '<section class="front toc">' + h(1,'Table of contents','contents') + '<ol>' + ''.join(f'<li><a href="#chapter-{n}">{n}. {escape(t)}</a></li>' for n,t in toc_titles) + '</ol><p>Links are clickable in the PDF and in compatible word processors.</p></section>'

body=[]
body.append(chapter(1,'Introduction to Ledgify',
 p('Ledgify is an organisation-scoped, double-entry accounting application. RC1 connects sales, purchases, banking, inventory, manufacturing, fixed assets, payroll, tax, foreign exchange, consolidation, reports and controlled AI assistance to a Django backend. The web interface is responsive, but wide financial tables may require horizontal scrolling on small screens.')+
 h(2,'Main capabilities')+ul(['Create and manage customers, suppliers, invoices, bills, quotes, orders and credits.','Post balanced journals and inspect account activity and source documents.','Import CSV bank statements, match transactions, cash-code genuine unmatched items and reconcile accounts.','Maintain perpetual weighted-average-cost inventory, stock counts, transfers and returns.','Maintain fixed assets, run accounting depreciation and record disposals.','Run manufacturing work in progress, payroll, tax, FX and full consolidation workflows within the documented limits.','Generate financial reports, ratios and supported CSV, Excel and PDF exports.','Use the AI Assistant for explanations and controlled proposals; it cannot autonomously post high-risk entries.'])+
 h(2,'Saving, approving and posting')+table(['Stage','Meaning','Accounting effect'],[
('Save/Draft','Stores a record for completion or review.','Normally none.'),('Approve','Confirms a commercial or payroll document may proceed.','For invoices and bills, approval posts the accounting entry.'),('Post','Writes a balanced journal to the general ledger.','Reports and account balances change.'),('Reverse/Void','Creates or applies a controlled correction while preserving history.','Original economic effect is neutralised according to the workflow.')])+
 note('warning','Responsibility','Do not approve, post, reverse, void or delete records unless you are authorised and hold appropriate supporting evidence. Posted records should normally be corrected through their source workflow or a documented reversal.')))

login_img = ''
if LOGIN.exists():
    login_img = f'<figure><img src="data:image/png;base64,{b64encode(LOGIN.read_bytes()).decode()}" alt="Ledgify sign-in page"><figcaption>Figure 1. Ledgify sign-in page (captured from the implemented application).</figcaption></figure>'
body.append(chapter(2,'Getting started',
 h(2,'System requirements')+p('Use a current version of Chrome, Edge, Firefox or Safari, a reliable network connection and a screen width that allows tables to be reviewed. JavaScript, cookies and local browser storage must be permitted. Obtain the correct Ledgify address and credentials from your administrator.')+
 h(2,'Sign in')+ol(['Open the Ledgify web address.','Enter the registered <strong>Email</strong> and <strong>Password</strong>.','Select <strong>Sign in</strong>.','If the account belongs to more than one organisation, select the required organisation. Always confirm the organisation shown in the header before entering data.'])+login_img+
 h(2,'Registration and forgotten passwords')+note('planned','Not currently available','Self-service registration, password reset, password change and two-factor authentication are not implemented in the current user interface/API. Ask an administrator to create or recover access through the approved support process.')+
 h(2,'Navigation')+p('The sidebar groups Dashboard, Sales, Purchases, Banking, Contacts, Inventory, Accounting, Fixed Assets, Manufacturing, Payroll, Tax, Reports, AI Assistant and Settings. Expand a group and select its page. On smaller screens use the mobile menu. The top bar contains organisation selection, global search, notifications and the user profile menu.')+
 h(2,'Sign out')+ol(['Open the user profile menu in the top-right corner.','Select <strong>Log out</strong>.','Close shared-browser tabs.'])+shot('Figure 2. Dashboard, sidebar, organisation switcher and top bar')))

body.append(chapter(3,'Initial organisation setup',
 h(2,'Recommended order')+ol(['Create or select the organisation.','Complete Organisation Profile and confirm legal name, registration/tax identifiers, address, country and time zone.','Confirm base currency and financial-year dates before posting.','Review the Chart of Accounts and control accounts.','Create bank accounts, tax rates, warehouses, products, asset categories and payroll components as required.','Add users and assign the least-privileged suitable role.','Enter verified opening balances through a balanced opening journal.','Review the Trial Balance and Balance Sheet before live processing.'])+
 h(2,'Organisation fields')+table(['Field','Purpose','Important rule'],[
('Organisation/Legal name','Name shown in settings and documents.','Use the registered or trading name required by the organisation.'),('Registration number','Company registration identifier.','Optional unless required by local rules.'),('Tax number','Organisation tax identifier.','Tax configuration is country-agnostic in RC1.'),('Country and address','Contact and reporting identity.','Keep current.'),('Base currency','Primary ledger currency.','Cannot safely be changed after postings; use FX workflows.'),('Time zone','Controls operational dates.','Choose the organisation’s working time zone.'),('Financial year','Defines reporting and close periods.','Create periods and lock completed periods.'),('Approval policy','May require a separate approver.','Do not let preparers approve their own work when separation is enabled.')])+
 note('warning','Opening balances','Opening balances must be supported by the previous system’s final Trial Balance. Debits and credits must agree. Use the agreed cut-over date and retain the import reconciliation.')+
 shot('Figure 3. Settings control centre and Organisation Profile')))

body.append(chapter(4,'Accounting fundamentals',
 h(2,'The accounting equation')+p('<strong>Assets = Liabilities + Equity.</strong> Assets are resources controlled by the business; liabilities are obligations; equity is the owners’ residual interest. Revenue increases profit and usually equity. Expenses reduce profit and equity.')+
 h(2,'Debit and credit reference')+table(['Account type','Normal balance','Increase','Decrease','Example'],[
('Asset','Debit','Debit','Credit','Bank, receivables, inventory'),('Liability','Credit','Credit','Debit','Payables, loans, tax due'),('Equity','Credit','Credit','Debit','Share capital, retained earnings'),('Revenue','Credit','Credit','Debit','Sales'),('Expense','Debit','Debit','Credit','Rent, wages, depreciation')])+
 h(2,'Double entry')+p('Every posted journal has equal total debits and credits. Northstar Trading Ltd invoices a customer £1,200: Debit Accounts Receivable £1,200; Credit Sales £1,200. Profit rises by £1,200 before related costs and tax, and the Balance Sheet shows a £1,200 receivable.')+
 h(2,'Accrual and cash accounting')+p('Accrual accounting recognises income when earned and expenses when incurred, regardless of payment. Cash accounting focuses on cash movement and may be acceptable only where applicable rules allow it. Ledgify’s invoice, bill and journal design is accrual-based.')+
 h(2,'Core terms')+ul(['<strong>Accounts receivable (AR):</strong> approved customer invoices less payments and credits.','<strong>Accounts payable (AP):</strong> approved supplier bills less payments and credits.','<strong>Trial Balance:</strong> account debit and credit totals at a date; it must balance.','<strong>General Ledger:</strong> detailed posted activity by account.','<strong>Financial period:</strong> reporting interval that may be open or locked.','<strong>Bank reconciliation:</strong> linking statement activity to ledger activity and explaining timing differences.','<strong>Depreciation:</strong> allocation of an asset’s depreciable cost across its useful life.','<strong>Cost of sales:</strong> cost assigned to goods sold; gross profit is sales less cost of sales.','<strong>Audit trail:</strong> who created, approved, posted, changed or reversed a record and when.'])+
 h(2,'VAT and tax')+p('RC1 includes country-neutral tax rates, periods, transactions and summary/preview pages. It does not perform electronic jurisdiction filing. “VAT” labels in the interface refer to transaction tax reporting; obtain professional advice before relying on a return.')+
 h(2,'Deletion, voiding and reversal')+p('Delete only unused drafts when the action is offered. Voiding changes a source document to a non-active state under its controlled rules. Reversal creates an offsetting accounting entry and preserves the original history. A reversed journal and its posted reversal remain visible in the ledger.')))

body.append(chapter(5,'Dashboard',
 p('Open <strong>Dashboard</strong> from the sidebar. It summarises connected financial information, recent invoices, recent transactions and cash-flow information. Cards and charts depend on the selected organisation and posted data.')+
 h(2,'Using the dashboard')+ol(['Confirm the organisation in the header.','Review summary cards and their dates.','Review Recent Invoices for overdue or unpaid items.','Review Recent Transactions for unusual values.','Use a card or linked item to open its detailed workflow where offered.'])+
 h(2,'Why dashboard and bank figures differ')+ul(['Approved invoices and bills affect profit and AR/AP before cash moves.','Unpresented payments and deposits create timing differences.','Statement rows may be imported but not reconciled.','Draft documents do not affect posted reports.','Date filters, foreign exchange rates, reversed entries or locked-period corrections may differ.'])+
 note('tip','Control','Use the Trial Balance, General Ledger and bank reconciliation—not dashboard cards alone—to substantiate period-end figures.')+shot('Figure 4. Dashboard summary cards, cash-flow chart and recent activity')))

body.append(chapter(6,'Sales and accounts receivable',
 h(2,'Customers')+p('Open <strong>Sales → Customers</strong> or <strong>Contacts → Customers</strong>. Use <strong>New Customer</strong> to enter identity and contact information. Open a customer to review summary cards, invoices, activity and statement; authorised users may edit details. Do not delete a customer with accounting history unless the workflow explicitly permits it.')+
 h(2,'Quotes and sales orders')+p('Open <strong>Sales → Quotes</strong> or <strong>Sales Orders</strong>. These commercial records do not recognise revenue merely by existing. Use supported detail actions to approve, convert, cancel or progress them. The new/edit route redirects to the integrated list workspace, so creation and editing occur there rather than on separate pages.')+
 h(2,'Create an invoice')+ol(['Open <strong>Sales → Invoices</strong> and choose <strong>New Invoice</strong>.','Select the customer.','Enter invoice date, due date, reference and currency shown by the form.','Add lines: description/product, quantity, unit price, income account and tax treatment where displayed.','Check subtotal, tax and total.','Save as draft. Review supporting evidence.','Approve when authorised. Approval posts the invoice.','Use the invoice details page to email, download or record payment where available.'])+
 h(2,'Invoice statuses')+table(['Status','Meaning','Permitted treatment'],[
('Draft','Saved but not posted.','Edit or delete if authorised.'),('Awaiting approval','Submitted for review.','Approver checks and approves or returns/corrects.'),('Approved','Posted and outstanding.','Do not freely edit; record payments or credits.'),('Partly paid','Some amount remains due.','Record only the remaining valid payment.'),('Paid','Nothing remains due.','No further payment allocation.'),('Void/Reversed','Controlled cancellation/correction.','Review the linked accounting history.')])+
 h(2,'Accounting entries')+table(['Event','Debit','Credit','Reports and balances'],[
('Approve £1,200 service invoice','Accounts Receivable £1,200','Sales £1,200','P&L revenue +£1,200; Balance Sheet AR +£1,200.'),('Receive £500','Bank £500','Accounts Receivable £500','AR falls to £700; bank rises £500; no new revenue.'),('Receive final £700','Bank £700','Accounts Receivable £700','AR becomes nil; invoice becomes Paid.'),('Approve credit/controlled reversal £1,200','Sales/returns £1,200','Accounts Receivable £1,200','Revenue and AR reduce, subject to tax and credit workflow.')])+
 h(2,'Payments and credits')+p('From Invoice Details or the eligible row action, select <strong>Record Payment</strong>, choose the bank account, enter payment date, amount, reference and optional notes, then confirm. An amount above the outstanding balance is rejected unless a specific credit workflow supports it. Credit Notes are under Sales and use draft, approval/application and void controls. Customer statements show invoices, payments, credits and running balance.')+
 note('warning','Posted sales','Never delete or edit an approved invoice to conceal a mistake. Use the available credit, void or reversal action and retain the reason and supporting documents.')+shot('Figure 5. Invoices list, New Invoice and Invoice Details')))

body.append(chapter(7,'Purchases and accounts payable',
 h(2,'Suppliers')+p('Open <strong>Purchases → Suppliers</strong>. Create a supplier with its name and available contact, account-number, payment-term and default-account information. Supplier Details and Statement show bills, payments, credits and balances.')+
 h(2,'Purchase orders')+p('Open <strong>Purchases → Purchase Orders</strong>. A purchase order records an intention to buy and does not itself recognise an expense or liability. Statuses are Draft, Approved, Partly received, Received, Billed and Cancelled. Integrated creation/editing occurs in the list workspace; dedicated new/edit URLs redirect there.')+
 h(2,'Enter and approve a bill')+ol(['Open <strong>Purchases → Bills</strong> and choose <strong>New Bill</strong>.','Select the supplier and enter supplier bill number/reference, bill date, due date and currency.','Add expense or product lines, quantities, prices, accounts and tax treatment.','Check totals and save Draft.','Submit for approval where the policy requires it.','Approve when evidence agrees. Approval posts the liability and expense/inventory entry.'])+
 h(2,'Bill statuses')+table(['Status','Meaning'],[('Draft','Editable and unposted.'),('Awaiting approval','Waiting for authorised review.'),('Approved','Posted and unpaid.'),('Partly paid','Some amount remains due.'),('Paid','Fully settled.'),('Void/Reversed','Controlled cancellation or reversal.')])+
 h(2,'Accounting entries')+table(['Event','Debit','Credit','Effect'],[
('Approve £600 electricity bill','Electricity Expense £600','Accounts Payable £600','P&L expense +£600; liability +£600.'),('Pay £250','Accounts Payable £250','Bank £250','Liability falls to £350; bank falls £250.'),('Pay remaining £350','Accounts Payable £350','Bank £350','Bill becomes Paid.'),('Immediate £90 stationery purchase','Stationery Expense £90','Bank £90','Expense rises and bank falls immediately.')])+
 p('Record payments from Bill Details or an eligible row action. Enter only the outstanding amount, bank account, date and reference. Supplier Credits reduce AP and may be applied or refunded using their controlled workflow. Attachments are not a verified general-purpose feature in RC1; retain supporting documents in the organisation’s approved document system.')+
 note('warning','Duplicate supplier invoices','Use the supplier’s invoice number consistently and check for duplicates before approval. Do not alter an approved bill to force agreement.')+shot('Figure 6. Bills list, bill form and payment dialogue')))

body.append(chapter(8,'Banking',
 h(2,'Bank accounts')+ol(['Open <strong>Banking → Bank Accounts</strong>.','Add a bank account and link it to one bank-class ledger account.','Enter identifying fields and opening information shown by the form.','Confirm the currency and active status before importing or posting.'])+
 h(2,'Balances')+table(['Balance','Meaning'],[('Bank balance','Informal term; confirm whether the bank’s live/statement figure or the ledger is meant.'),('Book/Ledger balance','Posted accounting movements in the linked ledger account.'),('Statement balance','Transactions supplied by the bank statement/import.'),('Reconciled balance','Statement activity matched or accounted for through the reconciliation workflow.')])+
 h(2,'Transactions and transfers')+p('Transactions show Money in and Money out with Unreconciled, Reconciled or Ignored status. Use the dedicated transfer workflow so both bank accounts are posted together. Do not represent an internal transfer as income or expense.')+
 h(2,'CSV statement import')+ol(['Open <strong>Banking → Statement Import</strong>.','Choose the bank account and CSV file.','Map or confirm date, description/reference and amount columns as prompted.','Preview the import. Review invalid and duplicate rows.','Complete only after totals and date range agree with the statement.'])+p('Import statuses include Pending, Previewed, Completed and Failed. Row statuses include Pending, Ready, Duplicate, Imported and Rejected. Live bank feeds are not configured; CSV is the verified ingestion method.')+
 h(2,'Reconciliation')+ol(['Open <strong>Banking → Reconciliation</strong> and choose the bank account.','Select an unreconciled statement row.','Review suggested existing invoices, bills, payments or ledger entries.','Match the row to an existing canonical record. Matching must not create a duplicate payment or journal.','If the row is a genuine fee, interest or other unmatched item, use <strong>Cash Coding</strong> with an appropriate non-control account.','Confirm the difference is zero and reconcile.'])+
 note('warning','Control accounts','Cash Coding and Bank Rules cannot post directly to Accounts Receivable or Accounts Payable control accounts. Match customer or supplier payments through their subledger workflows.')+
 h(2,'Rules and corrections')+p('Bank Rules provide deterministic suggestions and do not silently post. Review every suggestion. Unreconcile preserves history and reverses accounting where required; correct the source transaction, then reconcile again. Investigate non-zero differences, duplicate imports, wrong dates, bank fees, transfers and unpresented items.')+shot('Figure 7. Reconciliation workspace and statement import preview')))

body.append(chapter(9,'Chart of Accounts',
 p('Open <strong>Accounting → Chart of Accounts</strong>. Search or filter accounts; open Account Details for posted activity and balance. Accounts have Code, Name, Account type, Account class, status and cash-flow classification where configured.')+
 h(2,'Account codes')+p('Codes provide a stable sort order. A label such as <strong>Edit 1000</strong> means “edit the account whose code is 1000”; it is not a separate function. Common ranges vary, but a professional example is:')+
 table(['Range','Typical use','Examples'],[('1000–1999','Assets','1000 Bank; 1100 Accounts Receivable; 1200 Inventory'),('2000–2999','Liabilities','2000 Accounts Payable; 2100 Tax Payable'),('3000–3999','Equity','3000 Share Capital; 3200 Retained Earnings'),('4000–4999','Revenue','4000 Sales; 4100 Service Revenue'),('5000–5999','Cost of sales','5000 Cost of Goods Sold'),('6000–8999','Expenses/other','6000 Rent; 6100 Wages; 7000 Depreciation')])+
 h(2,'Create and maintain accounts')+ol(['Choose the create/new account action if your role permits it.','Enter a unique Code and descriptive Name.','Choose the Account type and Account class that reflect its economic purpose.','Set its cash-flow category where relevant.','Save and verify it appears as Active.'])+
 p('Codes must be unique within the organisation. Used or protected system/control accounts cannot be deleted. Deactivate or archive an unused account where available. Do not post manual entries directly to AR/AP control accounts; use sales and purchase workflows. Choose Bank only for genuine bank/cash ledgers.')+
 note('warning','Changing classification','Changing the type or class of an account with history can corrupt report interpretation. Obtain accountant approval and verify all affected reports.')+shot('Figure 8. Chart of Accounts and Account Details')))

body.append(chapter(10,'Journals',
 h(2,'Create a manual journal')+ol(['Open <strong>Accounting → Journals → New Journal</strong>.','Enter Journal date, Reference and Description.','Add at least two lines. Select active eligible accounts.','Enter either Debit or Credit on each line, never both.','Confirm total debits equal total credits.','Save Draft for review or Post when authorised and the period is open.'])+
 p('Journal statuses are Draft, Posted and Reversed. System-generated journals identify their source, such as Invoice, Bill, Payment, Bank, Inventory, Fixed Asset, Payroll, FX or Manufacturing. Journal Details shows creator/poster, source links, lines, totals and reversal information. Recurring journals are not confirmed as an active end-user workflow in RC1.')+
 h(2,'Examples')+table(['Event','Debit','Credit'],[('Owner introduces £10,000','Bank £10,000','Share Capital £10,000'),('Pay £1,000 rent immediately','Rent Expense £1,000','Bank £1,000'),('Accrue £300 electricity','Electricity Expense £300','Accrued Expenses £300'),('Prepay £1,200 annual insurance','Prepayments £1,200','Bank £1,200'),('Monthly insurance release','Insurance Expense £100','Prepayments £100'),('Monthly depreciation','Depreciation Expense £200','Accumulated Depreciation £200'),('Correct expense posted to repairs instead of rent','Rent Expense £250','Repairs Expense £250')])+
 h(2,'Reverse a journal')+ol(['Open Journal Details.','Confirm the original source and period. If it came from a subledger, use that source workflow instead.','Choose the reversal action, supply the required date/reason and confirm.','Verify the posted reversal and reports.'])+
 note('warning','Audit trail','Posted journals should not normally be deleted. Never use a manual journal to conceal an invoice, bill, payment, stock or bank error.')+shot('Figure 9. New Journal balanced entry grid and Journal Details')))

body.append(chapter(11,'Inventory',
 p('Open <strong>Inventory</strong>. Products includes goods and services; inventory-tracked goods hold quantity by warehouse. Warehouses are managed in the Products workspace even though the sidebar’s Warehouses label opens the same route.')+
 h(2,'Products and warehouses')+p('To add a product, enter required <strong>Code</strong> and <strong>Name</strong>, choose Goods or Service, and select <strong>Create product</strong>. Goods are created as inventory-tracked; services are not. The compact creation form defaults description blank, unit “each”, sales and purchase prices to £0.00 and status Active. Open Product Details to review stock summary and movement history. Add warehouses with required Code and Name; the first becomes default.')+
 h(2,'Perpetual weighted-average cost')+p('Ledgify uses perpetual WAC. If 10 units cost £10 each and 10 more cost £14 each, stock is 20 units costing £240, average £12. A sale of 5 units credits Inventory and debits Cost of Sales by £60. Historical layers are not rewritten.')+
 h(2,'Workflows')+ul(['<strong>Purchase Receipts:</strong> increase quantity and inventory value.','<strong>Sales Issues:</strong> reduce quantity at current WAC and recognise Cost of Sales.','<strong>Stock Transfers:</strong> move stock between warehouses without creating profit.','<strong>Customer Returns:</strong> restore eligible stock and reverse related cost.','<strong>Supplier Returns:</strong> reduce stock and supplier-related value.','<strong>Stock Adjustments:</strong> increase or decrease stock for verified corrections.','<strong>Stock Counts:</strong> compare counted and recorded quantity and post approved variance.','<strong>Inventory Reports:</strong> movement, valuation and reorder information.'])+
 table(['Event','Debit','Credit'],[('Purchase inventory £1,000 on account','Inventory £1,000','Accounts Payable £1,000'),('Sell goods costing £300','Cost of Sales £300','Inventory £300'),('Write off damaged stock £80','Inventory Loss/Expense £80','Inventory £80'),('Verified surplus £25','Inventory £25','Inventory Gain/Adjustment £25')])+
 note('warning','Negative inventory','An issue that would make stock negative is rejected. Receive or correct stock first; do not use an artificial adjustment without evidence.')+shot('Figure 10. Products, stock movements and stock adjustment workspace')))

body.append(chapter(12,'Fixed Assets',
 p('Open <strong>Fixed Assets → Asset Register</strong>. Visibility requires the <strong>view_fixed_assets</strong> permission. The connected RC1 workflow includes categories, register, activation/acquisition posting, depreciation, history and disposal.')+
 h(2,'Add and activate an asset')+ol(['Open Asset Register and choose the available add action.','Enter the asset name/code, category, acquisition date and Cost.','Enter Residual value, Useful life, Depreciation method and Depreciation start date.','Select Asset, Accumulated depreciation and Depreciation expense accounts.','Save and review the asset.','Activate only after agreeing the cost to supplier invoice/payment and supporting documents.'])+
 h(2,'Depreciation')+p('Straight-line depreciation is generally (Cost − Residual value) ÷ Useful life. A £12,000 asset with £0 residual value and five-year life depreciates £2,400 per year or £200 per month. Debit Depreciation Expense £200 and credit Accumulated Depreciation £200. Net book value becomes cost less accumulated depreciation. Reducing-balance capability must be selected only if offered for the category and professionally appropriate.')+
 h(2,'Run depreciation')+ol(['Open <strong>Fixed Assets → Depreciation</strong>.','Choose the period/date and preview eligible assets.','Review amounts, locked periods and prior runs.','Post when authorised.','Review depreciation history and the General Ledger.'])+
 h(2,'Disposal')+p('Record sale, scrap or write-off through the asset workflow. Ledgify removes cost and accumulated depreciation, records proceeds and posts gain or loss. Example: cost £12,000, accumulated depreciation £8,000, proceeds £5,000: book value £4,000 and gain £1,000.')+
 note('warning','Capital versus expense','Capitalise expenditure only when it creates a controlled resource with future benefit. Ordinary repairs and routine costs are usually expenses. RC1 calculates accounting—not tax—depreciation. Posted depreciation restricts editing; reverse/correct through controlled actions.')+shot('Figure 11. Asset Register, depreciation run and disposal')))

body.append(chapter(13,'Manufacturing',
 p('Manufacturing is visible to users with <strong>view_manufacturing</strong>. Open Manufacturing for Dashboard, Bills of Materials, Production Orders and Reports. It is connected to backend inventory, WAC, journal and Work in Progress (WIP) engines.')+
 h(2,'Bills of Materials')+ol(['Open <strong>Manufacturing → Bills of Materials</strong>.','Create or open a BOM for a finished product.','Maintain versioned component quantities and effective information.','Review and activate/approve only after engineering and costing checks.'])+
 h(2,'Production orders')+p('Production orders progress through permitted release, material issue/return, labour, overhead, subcontract cost, partial/final completion, variance and close actions. Available buttons depend on status and permission. Materials and production costs debit WIP; completion debits Finished Goods and credits WIP. Variances are posted to configured variance accounts.')+
 note('warning','Operational control','Do not issue materials or complete production before physical movement occurs. Demo fixture coverage is incomplete, so organisations should validate their own BOM, WIP, variance and scale scenarios before live use.')+shot('Figure 12. Manufacturing dashboard, BOM detail and Production Order')))

body.append(chapter(14,'Reports and financial analysis',
 p('Open <strong>Reports → Reports Centre</strong>. Connected reports include General Ledger, Trial Balance, Profit & Loss, Balance Sheet, Cash Flow, Aged Receivables and Aged Payables. Financial Analysis provides backend-calculated ratios and comparisons.')+
 table(['Report','What it shows','Key checks'],[
('Trial Balance','Cumulative debit and credit totals as of a date.','Total debits equal credits; investigate suspense and unexpected balances.'),('Profit & Loss','Revenue, cost and expenses for a period.','Dates, postings, account classification, accruals and reversals.'),('Balance Sheet','Assets, liabilities and equity at a date.','Accounting equation, AR/AP, bank, inventory and retained earnings.'),('General Ledger','Opening, detailed postings, running balance and journal links.','Source, date, account and reversal trail.'),('Cash Flow','Posted cash-account movements by configured category.','Cash account/category configuration and classification.'),('Aged Receivables','Open customer balances by age.','Payment/credit allocations and report date.'),('Aged Payables','Open supplier balances by age.','Payment/credit allocations and report date.'),('Financial Analysis','Liquidity, profitability, efficiency, leverage and working-capital ratios.','Formula/methodology, source availability and comparison period.')])+
 h(2,'Generate and export')+ol(['Open the report.','Set From/To or As at dates and any account/entity filters shown.','Choose comparison period where supported.','Generate/refresh the report.','Check totals and use account links for drill-down.','If authorised with <strong>export_reports</strong>, open <strong>Export</strong> and choose CSV, Excel or PDF.'])+
 p('CSV is best for plain data exchange; Excel is best for spreadsheet review; PDF is best for a fixed presentation. Preserve the unaltered system export and document any analysis changes. Not every specialist screen supports every format.')+
 h(2,'Why figures may be wrong')+ul(['Wrong organisation, date range or comparison.','Draft or unapproved documents.','Incorrect account type/class or cash-flow category.','Payment or credit not allocated.','Bank row imported but not reconciled.','Period correction or reversal dated outside the report.','Missing FX rate, tax configuration, inventory movement or depreciation run.'])+shot('Figure 13. Reports Centre, Profit & Loss and drill-down')))

body.append(chapter(15,'Tax, payroll, currencies and consolidation',
 h(2,'Tax')+p('Tax contains Tax Settings, Tax Rates, Tax Periods, Tax Summary, Tax Transactions and Tax Return Preview. Configure rates and effective dates, review transactions and preview a period return. Electronic filing and jurisdiction-specific adapters are not currently available; verify all tax treatment professionally.')+
 h(2,'Payroll')+p('Payroll tabs are Runs, Employees, Components, Payslips and Reports. Users with <strong>manage_employees</strong> can add employees and components; <strong>process_payroll</strong> controls runs; <strong>approve_payroll</strong> controls approval. Employee required fields are employee number, first name, last name, hire date and currency. Run statuses are Draft, Calculated, Approved, Posted and Paid. Payroll is an accounting engine; jurisdiction-specific statutory rules need an appropriate adapter and professional validation.')+
 h(2,'Currencies & FX')+p('FX stores dated exchange rates, supports foreign-currency documents and settlements, and provides controlled revaluation. There is no external market-rate feed. Confirm currency, rate date and source. Realised gains/losses arise on settlement; unrealised revaluation is posted through the controlled revaluation workflow. Base currency is safeguarded after postings.')+
 h(2,'Consolidation')+p('Consolidation supports configured groups, mappings, eliminations and full consolidation for 100%-owned subsidiaries. Non-controlling interests, equity method, proportionate consolidation, full cumulative translation adjustment and consolidated Cash Flow are not supported. Review entity periods, mappings, FX and eliminations before relying on group results.')+
 note('warning','Specialist advice','Tax, payroll, FX and consolidation can create statutory or complex reporting consequences. Use appropriately qualified reviewers.')+shot('Figure 14. Payroll, Tax, FX and Consolidation workspaces')))

body.append(chapter(16,'Settings',
 p('Open <strong>Settings</strong> or select <strong>Account & organisation settings</strong> from the profile menu. The control centre includes organisation profile, financial controls, linked workbenches, users/roles, AI safety and non-sensitive system information according to permission.')+
 table(['Area','RC1 status','What to do'],[
('Organisation Profile','Available','Maintain organisation identity and address.'),('Financial Settings','Available with safeguards','Maintain base currency/time zone/year controls before posting.'),('Financial Years/Periods','Available','Open, close and lock through linked workbenches.'),('Document numbering','Not currently available','No configurable sequence API; use authoritative system numbers.'),('Sales/Purchase defaults','Not currently available','Set values on each document.'),('Banking','Partly global','Maintain each account/rule in Banking.'),('Inventory/Fixed Assets/Tax/FX','Available through linked workbenches','Maintain domain-specific configuration.'),('Payroll/Manufacturing defaults','Partial','Configure components/BOM/order rather than global defaults.'),('AI Settings','Available','Maintain safety/provider behaviour where permitted.'),('Users','Partial','Roles/status supported; safe email invite/profile expansion remains.'),('Security','Partial','Password change and 2FA are not implemented.'),('Notifications','Not implemented','No preferences or delivery configuration.'),('Integrations/System info','Partial','Deployment configuration; limited non-sensitive status.')])+
 note('warning','Settings changes','Changing financial year, currency, tax, account mappings or approval policy can affect future posting and reporting. Record approval and test before applying changes.')+shot('Figure 15. Settings control centre')))

body.append(chapter(17,'Users, roles and permissions',
 p('Backend organisation membership and permissions are authoritative. The frontend hides some unavailable actions, but the server performs the final check. Typical roles are Owner, Admin, Accountant, Bookkeeper and Viewer; exact permission sets are displayed in Settings and may be fixed rather than customisable.')+
 h(2,'Manage access')+ol(['Open Settings and locate Users/Roles.','Review organisation membership, role and active status.','Use the available membership action to change a supported role or status.','Confirm the user signs into the correct organisation and sees only permitted modules.','Review access regularly and deactivate leavers promptly.'])+
 p('A complete email-invitation and user-profile expansion workflow is not verified in RC1. If no invite control is offered, ask an administrator to provision access. Custom roles are not implemented.')+
 h(2,'Least privilege and approvals')+ul(['Viewers should remain read-only.','Bookkeepers should enter routine transactions without unnecessary administrative authority.','Accountants review classifications, journals and period-end work.','Owners/Admins manage organisation-wide settings and access.','Where separate approval is required, the preparer must not approve their own document.'])+
 note('warning','Sensitive data','Financial, payroll, bank and export data must be shared only with authorised users. Never share passwords or authentication tokens.')))

body.append(chapter(18,'AI Assistant',
 p('Open <strong>AI Assistant</strong> from the sidebar if you have <strong>use_ai_assistant</strong>. The workspace supports conversations, organisation-scoped context, insights and controlled action proposals. Live text generation requires provider configuration; fallback and deterministic accounting tools may still be available.')+
 h(2,'Appropriate questions')+ul(['“Explain the change in gross margin this month.”','“Which overdue customer balances should I review?”','“Explain this liquidity ratio and its source data.”','“What should I check before closing the month?”','“Summarise unusual bank or expense activity for review.”'])+
 h(2,'Use safely')+ol(['Confirm the selected organisation and reporting period.','Ask a specific question without pasting passwords, secrets or unnecessary personal data.','Review cited/source figures and open the underlying report.','Treat suggestions as proposals, not posted facts.','Obtain authorised human approval and post through the normal source workflow.'])+
 p('The assistant cannot autonomously post high-risk accounting actions. It may be incomplete or mistaken and does not replace professional judgement. Users remain responsible for financial records, privacy and decisions.')+shot('Figure 16. AI Assistant conversation and controlled proposal')))

body.append(chapter(19,'Search, notifications and profile',
 h(2,'Global search')+p('Use the search control in the top bar; on mobile select the search icon. Enter a record name, number or reference. Search is organisation-scoped. Select a result to open its supported detail page. If nothing appears, confirm spelling, organisation, permission and whether the record is connected to the search service.')+
 h(2,'Notifications')+p('Select the bell icon. The current panel displays “No notifications” and explicitly states that notification delivery is not configured yet. Mark-as-read, preferences and linked notification workflows are <strong>not currently available</strong>.')+
 h(2,'Profile')+p('The profile menu displays name, email and organisation role, links to Account & organisation settings, offers organisation switching where more than one membership exists, provides Help & support, and includes Log out. Password/security self-service is not currently available.')+shot('Figure 17. Search, notification panel and profile menu')))

body.append(chapter(20,'Imports, exports and attachments',
 h(2,'Imports')+p('Bank statement CSV import is the verified end-user import workflow. Journal import/reversal components also exist for controlled journal workflows where exposed. Prepare CSV in the exact columns accepted by the preview, use ISO-style unambiguous dates where possible, keep one transaction per row and remove formulas/macros. Always preview and reconcile control totals.')+
 h(2,'Duplicate prevention')+p('Statement imports use preview and duplicate identification. Do not override duplicate warnings simply to make the statement total match. Compare bank account, date, amount and reference against previous imports.')+
 h(2,'Exports')+p('Supported report screens provide CSV, Excel and PDF through the Export menu when the user has <strong>export_reports</strong>. Printing may be available through PDF or the browser. Protect exported files, restrict recipients, use encrypted storage and delete temporary copies under the organisation’s retention policy.')+
 h(2,'Attachments')+note('planned','Not currently available as a general workflow','The code review does not verify a general attachment store for invoices, bills, assets or journals. Keep source documents in the organisation’s approved repository and use stable references in Ledgify.')))

body.append(chapter(21,'Period-end procedures',
 h(2,'Daily and weekly checks')+ul(['Review failed imports and unusual transactions.','Approve valid invoices/bills promptly and allocate payments.','Review overdue receivables/payables and negative/low stock warnings.','Retain source documents and resolve errors through controlled workflows.'])+
 h(2,'Month-end checklist')+ol(['Confirm all routine invoices, bills, credits, payments and bank transfers are entered.','Complete bank imports and reconcile every account to statement closing balances.','Review aged receivables/payables and investigate unallocated balances.','Review inventory movements, stock counts, valuation and GRNI-related items.','Post depreciation, payroll, accruals, prepayments and verified corrections.','Review tax transactions and period preview.','Review foreign balances/rates and revaluation where appropriate.','Run Trial Balance, P&L, Balance Sheet, Cash Flow and General Ledger checks.','Clear or explain suspense and unusual balances.','Obtain approval, export final reports and lock the period if available.'])+
 h(2,'Year-end checklist')+ol(['Complete all month-end work and reconcile subledgers to control accounts.','Confirm fixed asset additions, disposals and depreciation.','Review stock count and valuation.','Review provisions, accruals, prepayments, loans, equity and retained earnings.','Review tax/payroll obligations with advisers.','Run year-end close only with authorised accountant approval.','Preserve final reports, audit trail and backup evidence; close/lock periods according to policy.'])+
 note('warning','Period locking','A locked period rejects posting. Do not reopen it casually; document authority, reason and every resulting adjustment.')))

workflow_rows=[
('Set up an organisation','Settings → profile/currency/year → Chart of Accounts → bank/tax/warehouse settings → opening journal → verify Trial Balance.'),
('Customer and invoice','Customers → New Customer → Invoices → New Invoice → save Draft → approve → verify AR and Sales.'),
('Part/full customer payment','Invoice Details → Record Payment → bank/date/reference/amount → confirm → verify remaining due and bank ledger.'),
('Supplier and bill','Suppliers → New Supplier → Bills → New Bill → save/submit → approve → verify AP and expense/inventory.'),
('Pay supplier','Bill Details → Record Payment → bank/date/reference/amount → confirm → verify AP and bank.'),
('Create bank account','Banking → Bank Accounts → add and link bank-class ledger → verify currency/opening information.'),
('Reconcile statement','Statement Import → preview/complete → Reconciliation → match/cash code → confirm zero difference.'),
('New ledger account','Chart of Accounts → create → unique code/name/type/class → save Active → verify report placement.'),
('Manual journal','Journals → New Journal → date/reference/description → balanced lines → review → post.'),
('Fixed asset','Asset Register → add/configure accounts → activate → Depreciation → preview/post → verify history.'),
('Inventory adjustment','Inventory → Stock Adjustments → product/warehouse/quantity/reason/value → review → post → verify movement/valuation.'),
('Export reports','Reports Centre → report/dates/filters → generate/review → Export → CSV/Excel/PDF.'),
('User access','Settings → Users/Roles → membership role/status action where available → verify least privilege.')]
body.append(chapter(22,'Common workflows',p('Use this quick-reference only after reading the detailed module section.')+table(['Workflow','Steps and verification'],workflow_rows)+note('tip','Control totals','After any posted workflow, verify both the source record and the relevant General Ledger/report.')))

troubles=[
('Login failure','Wrong credentials, inactive account or unavailable server.','Re-enter details, check connection, then ask an administrator to confirm status.'),
('Missing authentication token','Session expired or browser storage cleared.','Log out/in; avoid blocked cookies/storage. Contact admin if repeated.'),
('Missing or invalid organisation ID','No selected membership or stale organisation context.','Select the organisation again and refresh. Admin checks membership.'),
('Authorization header must contain two space-delimited values','Malformed authentication header or proxy/client defect.','Sign out/in. Do not edit tokens. Administrator checks deployment/proxy logs.'),
('Permission denied','Role lacks the required permission.','Confirm organisation and ask Owner/Admin for justified access.'),
('Required fields missing','A compulsory field is blank.','Review highlighted fields and submit again.'),
('Invalid dates','Bad format, date order, closed or locked period.','Use date picker; correct period/date; obtain approval to reopen only if necessary.'),
('Duplicate account number/code','Code already exists.','Search Chart of Accounts and choose an authorised unique code.'),
('Unbalanced journal','Debit and credit totals differ.','Correct lines until totals match; do not add suspense without approval.'),
('Payment exceeds outstanding balance','Amount is above unpaid balance.','Enter only amount due or use an approved credit/overpayment workflow if offered.'),
('Bank reconciliation difference','Missing/duplicate/wrongly dated transaction or opening balance.','Compare statement line by line; investigate, do not force an adjustment.'),
('Report omits a transaction','Draft/unapproved, wrong period/org/account or reversed.','Open source and journal; correct status/filter/classification.'),
('Export not downloading','No data, no export permission or browser blocked download.','Generate report, allow download, check permission; administrator checks browser/server.'),
('Fixed Assets not visible','Missing view_fixed_assets permission.','Confirm role; administrator grants justified permission.'),
('Layout/mobile problem','Wide table or stale browser assets.','Scroll table, rotate device, zoom appropriately, refresh/update browser; report route and viewport.'),
('AI unavailable','Provider not configured or permission missing.','Use deterministic reports; administrator checks safe provider configuration.'),
('Negative inventory rejected','Issue exceeds available stock.','Receive/correct verified stock; never fabricate quantity.'),
('Posting rejected in locked period','Accounting period locked.','Use correct open date or obtain formal reopen approval.')]
body.append(chapter(23,'Troubleshooting',table(['Issue','Possible cause','Correction / escalation'],troubles)+note('warning','Safe support','Never send passwords, API keys, authentication tokens, full bank files or payroll exports in ordinary support messages. Provide organisation, page, time, non-sensitive reference and request ID where available.')))

body.append(chapter(24,'Internal controls and good practice',ul([
'Separate preparation, approval, payment and reconciliation where staffing permits.','Require supporting documents and record clear references/reasons.','Use sequential system document numbers and investigate gaps.','Reconcile bank, AR, AP, inventory, tax and payroll control balances regularly.','Review user access at least quarterly and immediately for leavers.','Lock completed periods and strictly control reopening.','Correct posted records through source workflows or reversals, preserving the audit trail.','Back up and test recovery; production readiness still requires verified managed PostgreSQL/PITR, object storage, monitoring, TLS and restore evidence.','Protect personal, payroll and banking data and minimise exports.','Review unusual vendors, changed bank details, duplicate invoices, round amounts and unexpected journals as fraud indicators.'])+note('tip','Four-eye review','Material journals, credits, payments, bank changes, payroll and period reopening should receive independent review.')))

gloss=[('Account','A ledger category used to classify transactions.'),('Accrual','Income/expense recognised when earned/incurred, not when cash moves.'),('Aged report','Open balances grouped by how long they have been outstanding.'),('Asset','A resource controlled by the organisation.'),('Audit trail','Recorded history of users, dates, changes and postings.'),('Bank reconciliation','Agreement of statement activity with accounting records.'),('Bill','A supplier document recording an amount owed.'),('Cash coding','Creating accounting for a genuine unmatched bank item.'),('Chart of Accounts','The organisation’s list of ledger accounts.'),('Control account','Ledger account supported by a detailed subledger, such as AR/AP.'),('Credit','The right-hand side of double entry; normally increases liabilities, equity and revenue.'),('Credit note','A document reducing an invoice or bill balance.'),('Debit','The left-hand side; normally increases assets and expenses.'),('Depreciation','Allocation of depreciable asset cost over useful life.'),('Draft','Saved but not posted.'),('Equity','Owners’ residual interest after liabilities.'),('FX','Foreign exchange.'),('General Ledger','Detailed posted transactions by account.'),('Gross profit','Revenue less cost of sales.'),('Invoice','A customer sales document recording an amount owed.'),('Journal','Balanced debit and credit entry.'),('Liability','An obligation owed by the organisation.'),('Net book value','Asset cost less accumulated depreciation.'),('Posting','Writing an authorised balanced entry to the ledger.'),('Reversal','Offsetting accounting entry preserving original history.'),('Trial Balance','Account debit and credit totals at a date.'),('VAT','Value Added Tax; Ledgify’s RC1 tax engine is country-neutral.'),('WAC','Weighted-average inventory cost.'),('WIP','Work in Progress: accumulated production cost not yet finished.')]
body.append(chapter(25,'Glossary',table(['Term','Plain-language definition'],gloss)))

faqs=[
('Does saving a draft affect reports?','Normally no. Reports use posted accounting.'),('When does an invoice affect revenue?','When approval posts its accounting entry.'),('Why is my profit not my bank balance?','Profit includes accruals and non-cash items; bank reflects cash movements.'),('Can I edit a paid invoice?','Do not freely edit it; use a controlled credit/void/reversal workflow.'),('Can I delete a posted journal?','Normally no. Reverse it with an explanation.'),('Why must journals balance?','Every economic event has equal debit and credit effects.'),('What are codes 1000 and 1100?','Identifiers for accounts, not separate functions.'),('Can cash coding use Accounts Receivable?','No; match customer payments through the sales subledger.'),('Does matching create a new payment?','Matching an existing canonical payment should reuse it, not duplicate it.'),('Are live bank feeds available?','No. CSV statement import is the verified method.'),('Can inventory go negative?','No; an issue that would create negative stock is rejected.'),('How is inventory valued?','Perpetual weighted-average cost.'),('Does a purchase order create an expense?','No; approval/receipt/bill workflows create relevant accounting.'),('Is depreciation tax depreciation?','No. RC1 implements accounting depreciation.'),('Can I file VAT electronically?','No. Review/preview exists; electronic filing is unsupported.'),('Does payroll calculate every UK statutory rule?','Not without an appropriate jurisdiction adapter and professional validation.'),('Where are notifications?','The bell panel exists, but delivery and preferences are not configured.'),('Can I reset my own password?','Not through the current UI/API; contact an administrator.'),('Can I create custom roles?','No. Use the available fixed roles/permissions.'),('Why can’t I see Fixed Assets?','Your membership may lack view_fixed_assets.'),('Can AI post a journal for me?','It cannot autonomously post high-risk accounting actions.'),('Are AI answers guaranteed correct?','No. Verify source records and obtain professional review.'),('Which exports are supported?','Supported report screens offer CSV, Excel and PDF to authorised users.'),('Can I attach supplier invoices?','A general attachment workflow is not verified in RC1.'),('Why does a report omit my draft?','Draft/unapproved records are normally excluded from posted reports.'),('When should I lock a period?','After reconciliation, review, approval and final exports.'),('Can I consolidate partly owned entities?','Advanced NCI/equity/proportionate methods are unsupported.'),('How do I switch organisation?','Use the header/profile organisation selector; verify context before entry.'),('Who should approve changes?','An authorised independent reviewer under your organisation’s policy.'),('What should I send support?','Non-sensitive organisation/page/time/reference/request ID—never secrets.')]
body.append(chapter(26,'Frequently asked questions',''.join(f'<h3>{i}. {q}</h3><p>{a}</p>' for i,(q,a) in enumerate(faqs,1))))

body.append(chapter(27,'Appendices',
 h(2,'A. Status reference')+table(['Record','Typical statuses'],[('Invoice/Bill','Draft; Awaiting approval; Approved; Partly paid; Paid; Void/Reversed'),('Customer/Supplier credit','Draft; Awaiting approval; Approved; Partly applied; Applied; Void'),('Journal','Draft; Posted; Reversed'),('Bank transaction','Unreconciled; Reconciled; Ignored'),('Purchase order','Draft; Approved; Partly received; Received; Billed; Cancelled'),('Pay run','Draft; Calculated; Approved; Posted; Paid'),('Account','Active; Inactive; Archived'),('Period','Open; Locked')])+
 h(2,'B. Example chart of accounts')+table(['Code','Account','Type/Class'],[('1000','Business Bank','Asset/Bank'),('1100','Accounts Receivable','Asset/Receivable control'),('1200','Inventory','Asset/Current asset'),('1300','Prepayments','Asset/Current asset'),('1500','Equipment at Cost','Asset/Fixed asset'),('1510','Accumulated Depreciation','Contra-asset'),('2000','Accounts Payable','Liability/Payable control'),('2100','Tax Payable','Liability/Current liability'),('2200','Accrued Expenses','Liability/Current liability'),('3000','Share Capital','Equity'),('3200','Retained Earnings','Equity'),('4000','Sales','Revenue/Sales'),('5000','Cost of Goods Sold','Expense/Cost of sales'),('6000','Rent','Expense/Operating expense'),('6100','Wages','Expense/Operating expense'),('7000','Depreciation','Expense/Operating expense')])+
 h(2,'C. Keyboard shortcuts')+p('No application-specific keyboard shortcuts are verified. Use standard browser and operating-system accessibility shortcuts.')+
 h(2,'D. Support')+p('In-application support link: <a href="mailto:support@ledgify.app">support@ledgify.app</a>. Replace or confirm this address before external publication. Include no secrets or unnecessary personal data.')+
 h(2,'E. Screenshot register')+p('Figure 1 is an authentic capture. Figures 2–17 are deliberately labelled placeholders pending access to a sanitised authenticated seed session. They are not invented screens.')))

css='''
@page { size:A4; margin:18mm 16mm 18mm 18mm; @bottom-center { content:"Ledgify Complete User Manual  •  " counter(page) " of " counter(pages); font:9pt Arial; color:#64748b } }
*{box-sizing:border-box} body{font-family:Arial,Helvetica,sans-serif;color:#172033;font-size:10.2pt;line-height:1.48;margin:0} a{color:#075985;text-decoration:none} h1,h2,h3{color:#0f3b4b;break-after:avoid} h1{font-size:24pt;border-bottom:2px solid #14b8a6;padding-bottom:7px}h2{font-size:15pt;margin-top:22px}h3{font-size:11.5pt;margin-top:15px}.cover{height:245mm;padding:45mm 18mm;background:linear-gradient(145deg,#082f49,#0f766e);color:white;break-after:page}.cover h1{font-size:38pt;color:white;border:0;margin:20mm 0 4mm}.brand{font-size:17pt;letter-spacing:6px;font-weight:700}.rule{width:45mm;border-top:4px solid #5eead4}.audience{margin-top:38mm;font-size:14pt;max-width:130mm}.confidential{position:absolute;bottom:20mm}.front{break-after:page}.chapter{break-before:page}p{margin:6px 0 9px}li{margin:4px 0}table{border-collapse:collapse;width:100%;margin:10px 0 16px;font-size:9pt;break-inside:auto}thead{display:table-header-group}tr{break-inside:avoid}th{background:#0f5666;color:white;text-align:left}th,td{border:1px solid #cbd5e1;padding:6px;vertical-align:top}tbody tr:nth-child(even){background:#f1f5f9}aside{border-left:5px solid;padding:9px 12px;margin:13px 0;break-inside:avoid}aside p{margin:4px 0}.warning{background:#fff7ed;border-color:#f97316}.tip{background:#ecfeff;border-color:#0891b2}.planned{background:#fefce8;border-color:#ca8a04}figure{margin:15px auto;text-align:center;break-inside:avoid}figure img{max-width:100%;border:1px solid #cbd5e1;box-shadow:0 2px 8px #94a3b8}figcaption{font-size:8.5pt;color:#475569;margin-top:5px}.placeholder div{height:65mm;border:2px dashed #94a3b8;background:#f8fafc;display:flex;flex-direction:column;align-items:center;justify-content:center;color:#64748b;font-weight:bold}.placeholder small{font-weight:normal;margin-top:8px}.toc li{margin:8px}.toc a{font-weight:600}.front h1{margin-top:15mm}
'''
html='<!doctype html><html><head><meta charset="utf-8"><title>Ledgify Complete User Manual</title><style>'+css+'</style></head><body>'+cover+control+toc+''.join(body)+'</body></html>'
(OUT/'Ledgify_Complete_User_Manual.html').write_text(html,encoding='utf-8')
print(f'Wrote HTML with {len(body)} chapters and {len(html.split())} words/tokens.')
